import { mkdirSync, writeFileSync, existsSync } from 'fs';
import { join, dirname, basename } from 'path';
import { findSkillFiles, parseKeywords } from './skill-reader.js';

/**
 * Write parsed skill files to the target repo.
 * Takes an array of { path, content } objects.
 */
export function writeSkillFiles(repoPath, files, options = {}) {
  const { dryRun = false, force = false } = options;
  const results = [];

  for (const file of files) {
    const fullPath = join(repoPath, file.path);
    const exists = existsSync(fullPath);

    if (dryRun) {
      const action = exists && !force ? 'would-skip' : exists ? 'would-overwrite' : 'would-create';
      results.push({ path: file.path, status: action, content: file.content });
      continue;
    }

    if (exists && !force) {
      results.push({ path: file.path, status: 'skipped', reason: 'already exists (use --force to overwrite)' });
      continue;
    }

    // Create directories
    mkdirSync(dirname(fullPath), { recursive: true });
    writeFileSync(fullPath, file.content, 'utf8');
    results.push({ path: file.path, status: exists ? 'overwritten' : 'created' });
  }

  return results;
}

/**
 * Generate skill-rules.json (v2.0) from existing skill files.
 * Uses skill-reader.js to parse skills.
 * Returns the rules object ready to write.
 */
export function extractRulesFromSkills(skillsDir) {
  const skillFiles = findSkillFiles(skillsDir);
  const skills = {};

  for (const skill of skillFiles) {
    const name = skill.frontmatter?.name || skill.name;
    const description = skill.frontmatter?.description || '';
    const patterns = skill.activationPatterns;
    const explicitKeywords = parseKeywords(skill.content);
    const isBase = name === 'base';

    // Derive additional keywords
    const derivedKeywords = deriveKeywords(name, description, patterns);
    const allKeywords = dedupeStrings([...explicitKeywords, ...derivedKeywords]);

    // Generate intent patterns from keyword pairs
    const intentPatterns = generateIntentPatterns(allKeywords, name);

    if (isBase) {
      skills[name] = {
        type: 'base',
        enforcement: 'suggest',
        priority: 'critical',
        scope: 'all',
        alwaysActivate: true,
        filePatterns: patterns,
        promptTriggers: {
          keywords: allKeywords,
          intentPatterns,
        },
      };
    } else {
      skills[name] = {
        type: 'domain',
        enforcement: 'suggest',
        priority: 'high',
        scope: 'all',
        alwaysActivate: false,
        filePatterns: patterns,
        promptTriggers: {
          keywords: allKeywords,
          intentPatterns,
        },
      };
    }
  }

  return {
    version: '2.0',
    skills,
  };
}

/**
 * Generate bash code for detect_skill_domain() function.
 * Takes a rules object (from extractRulesFromSkills) and generates
 * hardcoded bash if/elif patterns from filePatterns.
 */
export function generateDomainPatterns(rules) {
  if (!rules || !rules.skills) {
    return generateEmptyDetectFunction();
  }

  const clauses = [];

  for (const [skillName, config] of Object.entries(rules.skills)) {
    // Skip base skill -- it's always active, no pattern matching needed
    if (config.type === 'base' || config.alwaysActivate) continue;

    const patterns = config.filePatterns || [];
    if (patterns.length === 0) continue;

    const bashPatterns = patterns
      .map(p => globToBashPattern(p))
      .filter(Boolean);

    if (bashPatterns.length === 0) continue;

    // Deduplicate patterns per skill
    const uniquePatterns = [...new Set(bashPatterns)];

    const conditions = uniquePatterns
      .map(p => `[[ "$file" =~ ${p} ]]`)
      .join(' || ');

    clauses.push({ skillName, conditions });
  }

  if (clauses.length === 0) {
    return generateEmptyDetectFunction();
  }

  // NOTE: if/elif = first-match-wins. If a file matches multiple skills,
  // only the first skill in insertion order is detected. This matches
  // the tutorkit orchestrator's behavior.
  let body = '';
  clauses.forEach((clause, i) => {
    const keyword = i === 0 ? 'if' : 'elif';
    body += `    ${keyword} ${clause.conditions}; then\n`;
    body += `        detected_skills="${clause.skillName}"\n`;
  });
  body += '    fi';

  return `detect_skill_domain() {
    local file="$1"
    local detected_skills=""

    # Generated by aspens from skill-rules.json filePatterns
${body}

    echo "$detected_skills"
}`;
}

/**
 * Merge aspens hook config into existing settings.json.
 *
 * 1. If no existing settings -> return template as-is
 * 2. If existing has no hooks -> add hooks from template
 * 3. If existing has hooks -> merge per event type:
 *    - Detect existing aspens hooks by command path substring
 *      (skill-activation-prompt or post-tool-use-tracker)
 *    - Replace if found, append if not
 *    - Preserve non-aspens hooks
 * 4. Preserve all non-hooks keys
 */
export function mergeSettings(existing, template) {
  if (!existing) return template;

  // Clone to avoid mutations
  const merged = JSON.parse(JSON.stringify(existing));

  if (!template || !template.hooks) return merged;

  // If existing has no hooks, add them wholesale
  if (!merged.hooks) {
    merged.hooks = template.hooks;
    return merged;
  }

  // Merge per event type
  for (const [eventType, templateEntries] of Object.entries(template.hooks)) {
    if (!Array.isArray(templateEntries)) continue;

    if (!merged.hooks[eventType] || !Array.isArray(merged.hooks[eventType])) {
      // Event type doesn't exist or is malformed -- replace with template
      merged.hooks[eventType] = templateEntries;
      continue;
    }

    // Merge entries for this event type
    for (const templateEntry of templateEntries) {
      const templateCommands = extractHookCommands(templateEntry);
      const aspensCommands = templateCommands.filter(cmd => isAspensHook(cmd));

      if (aspensCommands.length === 0) {
        // Not an aspens hook — check for duplicates before appending
        const isDuplicate = merged.hooks[eventType].some(e =>
          JSON.stringify(e) === JSON.stringify(templateEntry)
        );
        if (!isDuplicate) {
          merged.hooks[eventType].push(templateEntry);
        }
        continue;
      }

      // Find existing entry that has an aspens hook matching this one
      let replaced = false;
      for (let i = 0; i < merged.hooks[eventType].length; i++) {
        const existingEntry = merged.hooks[eventType][i];
        const existingCommands = extractHookCommands(existingEntry);

        const hasMatchingAspens = existingCommands.some(cmd =>
          aspensCommands.some(ac => hookCommandsMatch(cmd, ac))
        );

        if (hasMatchingAspens) {
          // Replace the existing entry with the template entry,
          // but preserve any non-aspens hooks from the existing entry
          const nonAspensHooks = (existingEntry.hooks || []).filter(
            h => !isAspensHook(h.command || '')
          );
          const aspensHooks = (templateEntry.hooks || []).filter(
            h => isAspensHook(h.command || '')
          );

          const mergedEntry = { ...templateEntry };
          mergedEntry.hooks = [...aspensHooks, ...nonAspensHooks];

          // Preserve matcher from template if present, existing otherwise
          if (templateEntry.matcher) {
            mergedEntry.matcher = templateEntry.matcher;
          } else if (existingEntry.matcher) {
            mergedEntry.matcher = existingEntry.matcher;
          }

          merged.hooks[eventType][i] = mergedEntry;
          replaced = true;
          break;
        }
      }

      if (!replaced) {
        // No matching aspens hook found, append
        merged.hooks[eventType].push(templateEntry);
      }
    }
  }

  return merged;
}

// --- Internal helpers ---

const ASPENS_HOOK_MARKERS = ['skill-activation-prompt', 'post-tool-use-tracker'];

/**
 * Check if a command string is an aspens-managed hook.
 */
function isAspensHook(command) {
  if (!command || typeof command !== 'string') return false;
  return ASPENS_HOOK_MARKERS.some(marker => command.includes(marker));
}

/**
 * Check if two hook commands refer to the same aspens hook.
 */
function hookCommandsMatch(cmd1, cmd2) {
  if (!cmd1 || !cmd2) return false;
  return ASPENS_HOOK_MARKERS.some(marker => cmd1.includes(marker) && cmd2.includes(marker));
}

/**
 * Extract command strings from a hook entry.
 */
function extractHookCommands(entry) {
  if (!entry || !entry.hooks || !Array.isArray(entry.hooks)) return [];
  return entry.hooks
    .map(h => h.command || '')
    .filter(Boolean);
}

/**
 * Derive keywords from skill name, description first sentence, and directory names in file patterns.
 */
function deriveKeywords(name, description, filePatterns) {
  const keywords = [];

  // From skill name: split on hyphens
  if (name && name !== 'base') {
    const parts = name.split('-').filter(p => p.length > 2);
    keywords.push(...parts);
    // Also add the full name with spaces
    if (parts.length > 1) {
      keywords.push(parts.join(' '));
    }
  }

  // From description: first sentence
  if (description) {
    const firstSentence = description.split(/[.!?\n]/)[0].trim();
    if (firstSentence) {
      // Extract meaningful words (3+ chars, not common stop words)
      const words = firstSentence
        .toLowerCase()
        .split(/\s+/)
        .filter(w => w.length > 3 && !STOP_WORDS.has(w));
      keywords.push(...words.slice(0, 5));
    }
  }

  // From file patterns: extract directory names
  if (filePatterns && Array.isArray(filePatterns)) {
    for (const pattern of filePatterns) {
      const dirs = extractDistinctiveParts(pattern);
      keywords.push(...dirs);
    }
  }

  return dedupeStrings(keywords);
}

/**
 * Generate intent patterns from keywords.
 * Produces regex patterns matching common action + keyword combinations.
 */
function generateIntentPatterns(keywords, skillName) {
  if (!keywords || keywords.length === 0) return [];

  const patterns = [];
  const actionVerbs = '(create|update|fix|add|modify|change|debug|refactor|implement|build)';

  // For multi-word keywords, create direct patterns
  const multiWord = keywords.filter(k => k.includes(' '));
  for (const kw of multiWord) {
    const escaped = escapeRegex(kw);
    patterns.push(`${actionVerbs}.*${escaped}`);
    patterns.push(`${escaped}.*${actionVerbs}`);
  }

  // For the skill name itself (if multi-word when split on -)
  if (skillName && skillName.includes('-') && skillName !== 'base') {
    const parts = skillName.split('-');
    const namePattern = parts.join('.*');
    patterns.push(`${actionVerbs}.*${namePattern}`);
  }

  // Dedupe and limit
  return dedupeStrings(patterns).slice(0, 6);
}

/**
 * Convert a glob file pattern to a bash regex pattern.
 * Extracts the most distinctive directory or filename part.
 */
function globToBashPattern(glob) {
  if (!glob || typeof glob !== 'string') return null;

  // Remove leading **/ or */ patterns
  let cleaned = glob.replace(/^\*\*\//, '').replace(/^\*\//, '');

  // Handle dir/**/*.ext patterns (e.g., tests/**/*.test.js → /tests/)
  // Strip the /**/*.ext suffix first, then fall through to directory extraction
  cleaned = cleaned.replace(/\/\*\*\/\*\.[a-z.]+$/, '');

  // Remove trailing /** or /* patterns
  cleaned = cleaned.replace(/\/\*\*\/?\*?$/, '').replace(/\/\*$/, '');

  // If it's a specific file (has extension, no wildcards), use the filename
  if (cleaned.includes('.') && !cleaned.includes('*')) {
    const name = basename(cleaned)
      .replace(/\.[a-z]{1,4}$/, '');  // Strip last extension only
    if (name.length > 2) {
      return `/${name}`;
    }
    return null;
  }

  // For directory patterns, extract the most distinctive directory
  const parts = cleaned.split('/').filter(p =>
    p.length > 2 && !p.includes('*') && !GENERIC_DIRS.has(p)
  );

  if (parts.length > 0) {
    return `/${parts[parts.length - 1]}/`;
  }

  return null;
}

/**
 * Extract distinctive path parts from a file pattern (for keyword derivation).
 */
function extractDistinctiveParts(pattern) {
  if (!pattern) return [];
  const parts = pattern
    .replace(/\*\*/g, '')
    .replace(/\*/g, '')
    .split('/')
    .map(p => p.replace(/\.[^.]+$/, '')) // remove extensions
    .filter(p => p.length > 2 && !GENERIC_DIRS.has(p));
  return parts;
}

function generateEmptyDetectFunction() {
  return `detect_skill_domain() {
    local file="$1"
    local detected_skills=""

    # No domain patterns generated -- add skills with filePatterns first
    echo "$detected_skills"
}`;
}

function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function dedupeStrings(arr) {
  return [...new Set(arr.map(s => s.toLowerCase()))];
}

// Path segments too generic for keyword derivation or bash patterns
const GENERIC_DIRS = new Set([
  'src', 'app', 'lib', 'api', 'v1', 'v2',
  'utils', 'helpers', 'common', 'core', 'config',
  'types', 'public', 'assets', 'styles', 'scripts',
]);

const STOP_WORDS = new Set([
  'that', 'this', 'with', 'from', 'into', 'which', 'when', 'where',
  'what', 'they', 'them', 'then', 'than', 'have', 'been', 'will',
  'would', 'could', 'should', 'does', 'each', 'every', 'both',
  'through', 'during', 'before', 'after', 'above', 'below',
  'between', 'about', 'under', 'over', 'such', 'here', 'there',
  'these', 'those', 'other', 'some', 'most', 'very', 'also',
  'just', 'only', 'more', 'well', 'back', 'down', 'still',
]);
